name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.18.x", "1.19.x"]
        include:
        - go: 1.19.x
          os: "ubuntu-latest"
          latest: true
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: make build

    - name: Lint
      run: make lint
      # Lint rules change between versions of Go,
      # and it's sometimes not possible to comply with both.
      # Therefore, lint only with the latest Go version.
      if: matrix.latest

    - name: Test
      run: make test
